#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xamarin_android.Resource", IsApplication=true)]

namespace xamarin_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Ball = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int foosball_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int play = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int play_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int play_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tournament = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tournament_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tournament_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tvBackground = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001f
			public const int CreatorsID = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int DeleteTournament = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int FightButton = 2131034151;
			
			// aapt resource value: 0x7f050019
			public const int ID = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int InsertButton = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int InsertTournament = 2131034144;
			
			// aapt resource value: 0x7f050025
			public const int LeftID = 2131034149;
			
			// aapt resource value: 0x7f050000
			public const int ListView = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int Name = 2131034138;
			
			// aapt resource value: 0x7f050010
			public const int PIN = 2131034128;
			
			// aapt resource value: 0x7f050026
			public const int RightID = 2131034150;
			
			// aapt resource value: 0x7f05001c
			public const int ShowPlayersButton = 2131034140;
			
			// aapt resource value: 0x7f050023
			public const int ShowResults = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int ShowTournaments = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int TournamentFightID = 2131034148;
			
			// aapt resource value: 0x7f05001e
			public const int TournamentID = 2131034142;
			
			// aapt resource value: 0x7f050028
			public const int TournamentResultsText = 2131034152;
			
			// aapt resource value: 0x7f05001d
			public const int UpdateButton = 2131034141;
			
			// aapt resource value: 0x7f050007
			public const int add = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int bExisting = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int bHistory = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int bNew = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int bPlayCamera = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int bPlayFile = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int bTournament = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int etTeamName1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int etTeamName2 = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int name = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int score = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int surfaceView = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int t_list = 2131034121;
			
			// aapt resource value: 0x7f050018
			public const int t_player = 2131034136;
			
			// aapt resource value: 0x7f050003
			public const int team1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int team2 = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int teamName1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int teamName2 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int teamScore1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int teamScore2 = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int teams = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int tesk = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int textureView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_highscore = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_new_tournament = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_start = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int a_tournament = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int d_PIN = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int d_team_names = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int list_row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int list_tournament = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tournament = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TournamentResults = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int camera = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int file = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int history = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int no_connection = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int t_add = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int t_code = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int t_existing = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int t_go = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int t_new_cup = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int t_pin = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int t_ptname = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int tournament = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
